config/routes.rb
Rails.application.routes.draw do
  match '/pictures/top-ten' => 'pictures#index', :as => 'top-ten', :via => [:get]
  resources :pictures do
    get 'score', :on => :member
    get 'search', :on => :collection
    get 'home', :on => :collection
  end

  root 'pictures#home'
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	scope :top_ten, -> {order('score DESC')}

	def self.home
		where("created_at >= ? AND created_at < ?", Date.today, Date.tomorrow).order('created_at ASC')
  	end

	def self.daily_capybara(s)
		low = Random.new.rand(0..100)
		results = GoogleCustomSearchApi.search("capybara", {"searchType" => "image", "num" => "10", "imgSize" => "huge", "LowRange" => low, "highRange" => low + 9, "hq" => s})
		r = Random.new.rand(0..9)
		image = results.items[r].image.thumbnailLink
		return image
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  def index
    @pictures = Picture.top_ten.limit(10)
  end

  def home
    @pictures = Picture.home.limit(1)
  end

  def show
  end

  def new
    @picture = Picture.new
  end

  def edit
  end

  def create
    @picture = Picture.new(picture_params)
    respond_to do |format|
      if @picture.save
        @picture.update_attributes(:score => 1)
        format.html { redirect_to pictures_path, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def score
    @pictures = params[:page] == 'home' ? Picture.home : Picture.top_ten
    @picture = Picture.find(params[:id])
    @page = params[:page]
    @picture.update_attributes(:score => @picture.score + 1)
    respond_to do |format|
      format.js {}
    end
  end

  def search
    @picture = Picture.daily_capybara(params[:s])
  end

  private
    def set_picture
      @picture = Picture.find(params[:id])
    end

    def picture_params
      params.require(:picture).permit(:image, :score)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/_navigation.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to "Caypbara of the Day", '/', id: "logo", :class => 'pull-left'
    %nav
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Home",   '/'
        %li= link_to "Top Ten", top_ten_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Capybara
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render :partial => '/layouts/navigation' 
    .container
      .row
        = yield

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/_picture.html.haml
.col-md-6
	%h2.pull-left.index= picture_counter + 1
	.pull-left= image_tag picture.image, :class => 'img-thumbnail top-ten-image-' + picture_counter.to_s
	.pull-left
		.pull-left{:class => 'likes-' + picture_counter.to_s}
			= picture.score.to_s + ' Likes'
		%br/
		= link_to 'Like', score_picture_path(picture, :page => params[:action]), :class => 'btn btn-primary score-' + picture_counter.to_s, remote: true

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/home.html.haml
%p#notice= notice

.container.home
	.row
		.jumbotron 
			%h1.text-center Today's Capybara
		.container
			.row.centered
				.align-center
					#pictures
						= render @pictures
				%h6.pull-left.not_your_capybara <i>Not your capybara</i>? What kind of Capybara are you looking for?

				%form{:action => search_pictures_path, method: 'get'}
					= text_field_tag :s, nil, :class => 'pull-left form-control search-bar', :placeholder => 'sad, awesome, etc...'
					= submit_tag 'Search', class: 'pull-left btn btn-primary', name: nil

app/views/pictures/index.html.haml
%p#notice= notice
.container
  .row
    .jumbotron
      %h1.text-center Top Ten Capybaras
    #pictures.container
      = render @pictures

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/score.js.erb
<% @pictures.each_with_index do |p,index| %>
$('.top-ten-image-<%= index %>').attr('src', '<%= Picture.find(p.id).image %>');
$('.likes-<%= index %>').html('<%= Picture.find(p.id).score %> Likes');
$('a.score-<%= index %>').attr('href','/pictures/<%= p.id %>/score?page=<%= @page %>');
<% end %>

app/views/pictures/search.html.haml
%p#notice= notice

.container
  .row
    .jumbotron 
      %h1.text-center
        This is an image of a <pre>#{params[:s]}</pre> capybara

  = image_tag @picture, :class => 'img-thumbnail'
  = form_tag('/pictures')
  = hidden_field_tag 'picture[image]', @picture
  %br/
%div= submit_tag 'Like', :class => 'btn btn-primary'
%br/
.row.collapse
  Look for a different kind of Capybara?
  = form_tag(search_pictures_path, method: "get") do
    = text_field_tag :s, nil, :class => 'pull-left form-control search-bar'
    = submit_tag "Search", class: 'pull-left btn btn-primary'

app/views/pictures/show.html.haml
%p#notice= notice
%h1 Capybara of the Day
%p
  = image_tag(@picture.image)
  %br/
  Score:
  \#{@picture.score}
  (#{link_to 'Like', score_picture_path(@picture)})
  %br/
  %br/
  What Kind of Capybara are you looking for?
.row.collapse
  = form_tag(search_pictures_path, method: "get") do
    .large-8.small-9.columns
      = text_field_tag(:s)
    .large-4.small-3.columns
      = submit_tag("Search")
= link_to "View Top 10", pictures_path